version: "3"

services:
  nexus3:
    image: sonatype/nexus3:3.48.0
    expose:
      - 8080
      - 8081
      - 8082
      - 8083
    ports:
      - ${REGISTRY_PORT}:8080
      - ${NEXUS_PORT}:8081
      - ${ADDITIONAL_PORT}:8082
      - ${ADDITIONAL_PORT_2}:8083
    restart: unless-stopped
    volumes:
      - ./nexus-data:/nexus-data:z
    container_name: nexus3
    networks:
      - default

networks:
  default:
    external:
      name: $NEXUX_NETWORK
